### ISSUE TITLE
Event image and location

### ISSUE THREAD

**Issue by openforfuture** [Ths2-9Y-LqJt6/MeetupScraper#6]
This project is awesome and easy to use, thank you! 😸

Would be possible to get also the url of the **event image** and the **event location**?

Thanks! 🙏

**Comment by mrjones-plip** [comment]
done!  that was easy enough to do right quick.

**Comment by openforfuture** [comment]
awesome and fast! 😸

only two more things:
- wouldn't be better take the 750px JPEG version?
- also the google map link would be interesting, since the address is missing

I found that inside the page there's a JSON with a lot of polished data:
```
            "Venue:????????": {
              "__typename": "Venue",
              "id": "????????",
              "name": "...",
              "address": "...",
              "city": "...",
              "state": "...",
              "country": "..."
            },
```
Maybe scraping data from there could be more future proof and complete.
